### ISSUE TITLE
BLE Scanner in React Native (react-native-ble-plx) fails to connect when offline

### ISSUE THREAD

**Issue by thomasaugot** [Polidea/react-native-ble-plx#1125]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active).
- [X] I'm running the latest version

### Question

Hi everyone,

We are trying to figure what in our Blescanner code is causing some failures while in offline mode. 

With network: It all works just fine.

Here are the logs I get when **online**: 
```
 LOG  CLICK ON 0C:B8:15:F3:89:12
 LOG  ====================================== START ======================================
 LOG  CHECK CONNECTED DEVICES OK :
 LOG  LE TABLEAU ETAIT VIDE
 LOG  AMORCE CONNEXION
 LOG  TRY TO CONNECT TO CURRENT DEVICE : 0C:B8:15:F3:89:12
 LOG  Device 0C:B8:15:F3:89:12 connecté
 LOG  CURRENT DEVICE CONNECTION OK
 LOG  CURRENT DEVICE CHARACTERISTICS OK
 LOG  CURRENT DEVICE MESSAGE SENDING OK
 LOG  CURRENT DEVICE DISCONNECTION OK
 LOG  ====================================== END ======================================
 LOG  {"response": {}, "status": "success"}
```

Now going **offline**, here is what happens: The function is fired without problem but will never reach the disconnectToDevice(deviceId):

```
 LOG  CLICK ON 0C:B8:15:F3:89:12
 LOG  ====================================== START ======================================
 LOG  CHECK CONNECTED DEVICES OK :
 LOG  LE TABLEAU ETAIT VIDE
 LOG  AMORCE CONNEXION
 LOG  TRY TO CONNECT TO CURRENT DEVICE : 0C:B8:15:F3:89:12
 LOG  Device 0C:B8:15:F3:89:12 connecté
 LOG  CURRENT DEVICE CONNECTION OK
 LOG  CURRENT DEVICE CHARACTERISTICS OK
 LOG  CURRENT DEVICE MESSAGE SENDING OK
 WARN  Possible Unhandled Promise Rejection (id: 3):
BleError: Device 0C:B8:15:F3:89:12 is not connected
BleError: Device 0C:B8:15:F3:89:12 is not connected
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:27106:64)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:159401:322)
    at call (native)
    at BleError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:159434:26)
    at parseBleError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:159463:30)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:160064:82)
    at throw (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:28357:26)
    at _throw (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:28379:29)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/2sw813f4/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/Release/2sw813f4/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:34988:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:34867:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:34912:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:35118:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:3282:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:3056:45)
    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:3255:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:3055:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.oslysolutions&modulesOnly=false&runModule=true:3049:33) 
```

As per what the logs say, it seems like the connection with the device gets lost on the way... Or am I wrong?

#### Library version: 
    - "react-native": "0.72.4",
    - "react-native-ble-plx": "^3.0.0",
    - "react-native-bluetooth-state-manager": "^1.3.5",
#### Platform: 
    - Android

I have tried using a setTimeout() to force setIsDoorOpening(false) after a few seconds but it creates bugs since the disconnection is never actually made. The craziest is that the mechanism it is supposed to activate when we fire the function still works just fine, either in online or offline mode. We just can't figure out why when offline, it never disconnects after firing the function. 

Here is the full code: 

```

    export default function BleReader({
  serviceUUID,
  id_maintenancier,
  id_permanent,
  id_building,
  id_gestionnaire,
}: Props) {
  const {
    devices,
    scanDevices,
    loading,
    initBleScanner,
    sendDataToDevice,
    devicesConnectedToTheService,
    disconnectToDevice,
    requestPermissions,
  } = useBleDevice(serviceUUID);

  const [refreshing, setRefreshing] = useState<boolean>(false);
  const [isDoorOpening, setIsDoorOpening] = useState<boolean>(false);

  useEffect(() => {
    initBleScanner(serviceUUID);
  }, [initBleScanner, serviceUUID]);

  const onRefresh = useCallback(async () => {
    requestPermissions;
    const listOfDevicesConnected = await devicesConnectedToTheService(
      serviceUUID,
    );
    await Promise.all(
      listOfDevicesConnected.map(device => {
        return disconnectToDevice(device.id);
      }),
    );

    setRefreshing(true);
    scanDevices(serviceUUID).then(() => {
      setRefreshing(false);
      setIsDoorOpening(false);
    });
  }, [
    requestPermissions,
    scanDevices,
    devicesConnectedToTheService,
    disconnectToDevice,
    serviceUUID,
  ]);

  const onClickDevice = async (device: Device) => {
    console.log(`CLICK ON ${device.id}`);
    if (isDoorOpening) {
      setIsDoorOpening(false);
      showMessage({
        message: 'Oups',
        description: 'Une autre instance est en cours',
        type: 'danger',
        autoHide: true,
        duration: 5000,
        hideOnPress: true,
        icon: 'warning',
      });
      return;
    }
    setIsDoorOpening(true);
    await sendDataToDevice(device.id);
    const currentDateTime = new Date();
    if (!id_maintenancier && !id_permanent) {
      console.log(
        'Erreur',
        'Aucun id detecté, revoir le code pour Rôle 3, visiteur',
      );
    } else if (id_permanent && !id_maintenancier) {
      const historique_permanent = await alimenter_histo_permanent(
        id_permanent,
        id_building,
        id_gestionnaire,
        currentDateTime,
        device.name,
      );
      console.log(historique_permanent);
    } else if (id_maintenancier && !id_permanent) {
      if (id_gestionnaire) {
        const historique_temporaire = await alimenter_histo_temporaire(
          id_maintenancier,
          id_building,
          id_gestionnaire,
          currentDateTime,
          device.name,
        );
        console.log(historique_temporaire);
      }
    }
    setIsDoorOpening(false);
  };

```

and the custom hook we've added: 

``` 

    export default function useBleDevice(serviceUUID: string) {
  const manager = useRef(new BleManager());

  const [loading, setLoading] = useState<boolean>(false);
  const [devices, setDevices] = useState<Device[]>([]);

  const requestPermissions = useCallback(
    async (callback: PermissionCallBack) => {
      if (Platform.OS === 'android') {
        const apiLevel = await DeviceInfo.getApiLevel();
        if (apiLevel < 31) {
          const grantedStatus = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
          );
          if (grantedStatus === PermissionsAndroid.RESULTS.GRANTED) {
            console.log(grantedStatus);
            callback(grantedStatus === PermissionsAndroid.RESULTS.GRANTED);
            enableBluetooth();
          } else if (grantedStatus === PermissionsAndroid.RESULTS.DENIED) {
            console.log(grantedStatus);
            callback(grantedStatus === PermissionsAndroid.RESULTS.DENIED);
            enableBluetooth();
          } else if (
            grantedStatus === PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN
          ) {
            console.log(grantedStatus);
            callback(grantedStatus === PermissionsAndroid.RESULTS.DENIED);
            enableBluetooth();
          }
        } else {
          const result = await requestMultiple([
            PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
            PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
            PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
          ]);
          if (
            result['android.permission.BLUETOOTH_CONNECT'] ===
            PermissionsAndroid.RESULTS.GRANTED
          ) {
            enableBluetooth();
            callback(true);
          } else {
            callback(false);
          }
        }
      } else {
        callback(true);
      }
    },
    [],
  );

  const enableBluetooth = async () => {
    const isBluetoothEnabled = await BluetoothStateManager.requestToEnable();
    if (!isBluetoothEnabled) {
      await BluetoothStateManager.enable();
    }
  };

  const openLocationSettings = async () => {
    try {
      await Linking.openSettings();
    } catch (error) {
      console.log(error);
    }
  };

  const scanDevices = useCallback((devicesUUID: string) => {
    return new Promise(resolve => {
      setTimeout(function () {
        resolve(true);
        setLoading(false);
        manager.current.stopDeviceScan();
      }, 1000);

      setLoading(true);
      setDevices([]);

      manager.current.startDeviceScan(
        null,
        {allowDuplicates: false},
        (error, device) => {
          // c'est le callback quand un device est scanné par la librairie
          if (error) {
            // si il y a une erreur on l'affiche et on return (ca veut dire qu'on fait pas ce qu'il y a en dessous)

            return;
          }

          if (device?.serviceUUIDs?.includes(devicesUUID)) {
            setDevices(prev => {
              if (!prev.map(d => d.name).includes(device.name)) {
                return [...prev, device];
              }
              return prev;
            });
          }
        },
      );
    });
  }, []);

  const sendDataToDevice = async (deviceId: string) => {
    manager.current.destroy();
    const connectionManager = new BleManager();
    console.log(
      '====================================== START ======================================',
    );
    const listOfconnectedDevicesToTheService =
      await devicesConnectedToTheService(serviceUUID);
    console.log(
      `CHECK CONNECTED DEVICES OK : ${listOfconnectedDevicesToTheService}`,
    );
    if (listOfconnectedDevicesToTheService.length !== 0) {
      console.log('ENTER IN IF');
      await Promise.all(
        listOfconnectedDevicesToTheService.map(
          currentDeviceConnectedToTheService =>
            disconnectToDevice(currentDeviceConnectedToTheService.id),
          console.log('ENTER IN MAP'),
        ),
      );
      console.log('ALL DEVICES DISCONNECTION OK');
    } else {
      console.log('LE TABLEAU ETAIT VIDE');
    }
    console.log('AMORCE CONNEXION');
    await connectToDevice(deviceId);
    console.log(`TRY TO CONNECT TO CURRENT DEVICE : ${deviceId}`);
    if (await connectionManager.isDeviceConnected(deviceId)) {
      console.log(`Device ${deviceId} connecté`);

      console.log('CURRENT DEVICE CONNECTION OK');
      const currentDevice =
        await connectionManager.discoverAllServicesAndCharacteristicsForDevice(
          deviceId,
        );
      console.log('CURRENT DEVICE CHARACTERISTICS OK');
      const currentDeviceCharacteristics =
        await currentDevice.characteristicsForService(serviceUUID);

      const firstMessageSentToDevice = 'A';

      await connectionManager.writeCharacteristicWithResponseForDevice(
        deviceId,
        serviceUUID,
        currentDeviceCharacteristics[0].uuid,
        base64.encode(firstMessageSentToDevice),
      );
      console.log('CURRENT DEVICE MESSAGE SENDING OK');
      await disconnectToDevice(deviceId);
      console.log('CURRENT DEVICE DISCONNECTION OK');
    } else {
      console.log('SOMETHING WENT WRONG');
    }
    connectionManager.destroy();
    console.log(
      '====================================== END ======================================',
    );
  };

  const initBleScanner = useCallback(
    (UUID_DEVICE: string) => {
      requestPermissions((permissionsGranted: boolean) => {
        if (permissionsGranted) {
          // Code pour continuer avec le scan
          const subscription = manager.current.onStateChange(state => {
            if (state === 'PoweredOn') {
              scanDevices(UUID_DEVICE);
              subscription.remove();
            }
          }, true);
        } else {
          Alert.alert(
            'Activation de la permission nécessaire',
            "Veuillez activer la permission pour faire fonctionner l'application",
            [
              {
                text: 'OK',
                onPress: () => {
                  openLocationSettings();
                },
              },
            ],
          );
        }
      });
    },
    [scanDevices, requestPermissions],
  );

  const connectToDevice = async (deviceId: string) => {
    return manager.current.connectToDevice(deviceId);
  };

  const disconnectToDevice = (deviceId: string) => {
    return manager.current.cancelDeviceConnection(deviceId);
  };

  const isDeviceConnected = (deviceId: string) => {
    return manager.current.isDeviceConnected(deviceId);
  };

  const cancelDeviceConnection = (deviceId: string) => {
    return manager.current.cancelDeviceConnection(deviceId);
  };

  const devicesConnectedToTheService = async (servicesUUID: string) => {
    const listOfConnectedDevices = await manager.current.connectedDevices([
      servicesUUID,
    ]);
    return listOfConnectedDevices;
  };

  return {
    devices,
    scanDevices,
    loading,
    sendDataToDevice,
    initBleScanner,
    connectToDevice,
    disconnectToDevice,
    isDeviceConnected,
    cancelDeviceConnection,
    devicesConnectedToTheService,
    requestPermissions,
  };
}

```

I hope someone can help, I've been on it for hours and couldn't ever find out what's going on here:)
Thanks in advance!

**Comment by thomasaugot** [comment]
If someone ever reads this, I found out later the reason why. 
At the end of the BleReader component's code, I was firing the function alimenter_histo_temporaire(), which was actually performing an API call from another file. I didn't implement a logic to have this function working when offline, resulting in the rest of the code in my BLEReader landing in the catch after failing at this line. I moved the function a few lines upper to have the expected behaviour. Solved
