### ISSUE TITLE
Crash during scanning

### ISSUE THREAD

**Issue by sebirdman** [Polidea/react-native-ble-plx#286]
```
java.lang.IllegalArgumentException: Bad position 90/62
	 at java.nio.Buffer.position(Buffer.java:249)
	 at com.polidea.rxandroidble.internal.util.UUIDUtil.extractUUIDs(UUIDUtil.java:100)
	 at com.polidea.rxandroidble.internal.operations.LegacyScanOperation$1.onLeScan(LegacyScanOperation.java:39)
	 at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:2448)
	 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:478)
	 at android.os.Handler.handleCallback(Handler.java:790)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loop(Looper.java:164)
	 at android.app.ActivityThread.main(ActivityThread.java:6494)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I'm seeing the following crash sometimes while scanning.

**Comment by dariuszseweryn** [comment]
Apparently your peripheral broadcasts a malformed advertisement packet or there is a bug in the `RxAndroidBle`
