### ISSUE TITLE
NullPointerException detected in Pre Launch Report

### ISSUE THREAD

**Issue by MBach** [Polidea/react-native-ble-plx#795]
## Question

When publishing a new beta of my App, I can see the following ANR in the developer console (reported multiple times)

For example, for Moto E5 Play or Nokia 1:

```
FATAL EXCEPTION: mqt_native_modules
Process: (my process) PID: 11983
java.lang.NullPointerException: Attempt to invoke interface method 'void com.polidea.multiplatformbleadapter.BleAdapter.stopDeviceScan()' on a null object reference
	at com.polidea.reactnativeble.BleClientManager.stopDeviceScan(BleClientManager.java:196)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:164)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:764)
```

Is it possible to happen in real life situation?

At line 196 in BleClientManager.java https://github.com/Polidea/react-native-ble-plx/blob/64f0f6d7150bfcffdbb9d58f9981dc1cb1afa47c/android/src/main/java/com/polidea/reactnativeble/BleClientManager.java#L196

and everywhere in the class, the bleAdapter instance is not protected with a simple null check.

Is it worth to add them?

Regards

**Comment by Joao360** [comment]
Having the same issue. When the component is unmounting I'm doing stopDeviceScan before the destruction of the manager and still gives me this error.
